dist: trusty

language: cpp

env:
  global:
    - GH_REPO_NAME: FitTestBeamData2017
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/cmadrid1/FitTestBeamData2017.git
    - TARGET_BRANCH: master
    - secure: "NaC04+uMsQ3SpLwyQcCVvCMFvExgGrVTDc4CplYYq4cTrE77L4cQ3MlbGaasjGcAfo9Umglgd6UHjJuSgcNgu5dUYp22HOzb7vxOFG1XpJIOz3p/01d8+K9wv0sz5MvxlekI8G6F/42FCGvQwJRhu/C5ydtjIf6GBwg24PvHxgEKhzDZtXBaOoMAXdjss9SLuYVvUijc2dTfzsnkiZ233FwlRbEKeUjHok3Ugc/w87WwTdsOHIXdJJAtC8qaGkppd6Q+GciDz7RKWsS9AFlPzpxo3ypWS9BgGQ6k3rNITIaFg25HDfZLaseu2PJQeAOYCOSjGdRNvgT0NYIFAot32GWJkJ19hn6D0fbIFXsTl/vCrEUuC2JQbmIA9pCWn9jvPvrtgvYAFwcm1TDH5Dj9bftwUv9C2yYvIdez8z9GKQIvHeAnYrx2oTylf2vaK2so8Ayc9yEiLA+Oh+74ZO6a2Z6ZH/cIOWIZP2dmXmbRtBElLemz4/8fmVq2oacgLu2o0EF7nCqwdsOq9ljTG9VnU417CcQ4oz8Y5ETVxocDWcAgNUEev4cyZcIi2ep9TTFD8ZDP1qhRi+f9lx8J2LBycnx34Wt7JuZAZ86ZwbzbL0Gul68/MeM71dLtrsQTJ3pNHr4jCiyXj3Im2cSltxKwN4v00hGmGC/0F6c7VLsdyrk="

branches:
  only:
    - /.*/

before_install:
- sudo apt-get -qq update
- sudo apt-get install -qq autofs attr gdb git uuid-dev uuid fuse
- wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
- sudo dpkg -i cvmfs-release-latest_all.deb
- sudo apt-get update
- sudo apt-get install -qq cvmfs cvmfs-config-default
- sudo cvmfs_config setup
- sudo echo "CVMFS_HTTP_PROXY=\"DIRECT\"" | sudo tee /etc/cvmfs/default.local > /dev/null
- sudo echo CVMFS_REPOSITORIES=cms.cern.ch | sudo tee -a /etc/cvmfs/default.local > /dev/null
- sudo service autofs restart
- cvmfs_config probe
- sudo cvmfs_config chksetup
- sudo docker pull $DOCKER_CONTAINER

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

compiler:
  - gcc

script:
  - g++ -g -O3 `root-config --glibs --cflags` fittingClass/mipFitsSiPM.C -o mipFitsSiPM

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

notifications:
email: false